package com.android.baihuahu.core.utils;

/**
 * Dylan
 */
public class KeyConst {
    public static final String id = "id";
    public static final String loginName = "loginName";
    public static final String username = "username";
    public static final String attachment = "attachment";
    public static final String password = "password";//密码
    public static final String smsCode = "smsCode";//短信验证码
    public static final String loginMode = "loginMode";//注册渠道    （1手机，2QQ，3微信，4新浪微博）
    public static final String APP_TYPE_ID = "appTypeId";//平台类型（0表示安卓)
    public static final String writeCycle = "writeCycle";
    public static final String Supplier_Material = "Supplier_Material";
    public static final String CHECK_AREA_TYPE = "CHECK_AREA_TYPE";
    public static final String newPassword = "newPassword";
    public static final String oldPassword = "oldPassword";
    public static final String writeValue = "writeValue";
    public static final String signAttachment = "signAttachment";
    public static final String title = "title";
    public static final String dept = "dept";
    public static final String Bearer = "Bearer ";
    public static final String agreeReject_recall = "agreeReject_recall";//手机型号
    public static final String system = "system";

    public static final String grant_type = "grant_type";
    public static final String selectPosition = "selectPosition";
    public static final String inspectDate = "inspectDate";
    public static final String pic = "pic";
    public static final String areaId = "areaId";
    public static final String inspectArea = "inspectArea";
    public static final String isDanger = "isDanger";

    public static final String authType = "authType";
    public static final String rectifyDate = "rectifyDate";
    public static final String planId = "planId";
    public static final String checkOpinion = "checkOpinion";
    public static final String checkStatus = "checkStatus";

    public static final String name = "name";
    public static final String value = "value";
    public static final String url = "url";
    public static final String Authorization = "Authorization";
    public static final String Content_Type = "Content-Type";

    public static final String file = "file";
    public static final String fileName = "fileName";
    public static final String type = "type";
    public static final String numbers = "numbers";
    public static final String status = "status";
    public static final String commit = "commit";
    public static final String source = "source";
    public static final String piece = "piece";
    public static final String rectifyOpinion = "rectifyOpinion";
    public static final String signerName = "signerName";
    public static final String signer = "signer";
    public static final String processId = "processId";
    public static final String unit = "unit";
    public static final String OBJ_INFO = "OBJ_INFO";
    public static final String access_token = "access_token";
    public static final String supplier = "supplier";
    public static final String groupName = "groupName";
    public static final String times = "times";
    public static final String employeeSex = "employeeSex";
    public static final String employeeStatus = "employeeStatus";
    public static final String employeeOrder = "employeeOrder";
    public static final String employeeType = "employeeType";
    public static final String theme = "theme";
    public static final String bizWagesWorkerList = "bizWagesWorkerList";
    public static final String employeeBirthday = "employeeBirthday";
    public static final String employeeEmail = "employeeEmail";
    public static final String children = "children";
    public static final String inspectPic = "inspectPic";
    public static final String dangerPic = "dangerPic";
    public static final String rectifyPic = "rectifyPic";
    public static final String inspectInfo = "inspectInfo";

    public static final String dangerDesc = "dangerDesc";
    public static final String Construction_Unit = "Construction_Unit";
    public static final String Supervision_Unit = "Supervision_Unit";
    public static final String Design_Unit = "Design_Unit";
    public static final String GENDER = "GENDER";
    public static final String LEAVE_TYPE = "LEAVE_TYPE";//投资
    public static final String length = "length";
    public static final String period = "period";//工期
    public static final String startTime = "startTime";
    public static final String pstartDate = "pstartDate";
    public static final String pendDate = "pendDate";
    public static final String endTime = "endTime";
    public static final String code = "code";

    public static final String buildOrg = "buildOrg";
    public static final String buildLocation = "buildLocation";
    public static final String pcycle = "pcycle";
    public static final String pvalue = "pvalue";
    public static final String String = "String";
    public static final String thirdBillId = "thirdBillId";
    public static final String totalAmount = "totalAmount";

    public static final String billDetailId = "billDetailId";
    public static final String error = "error";
    public static final String inspectResult = "inspectResult";

    public static final String qualityId = "qualityId";
    public static final String securityId = "securityId";
    public static final String dangerId = "dangerId";
    public static final String feedback = "feedback";
    public static final String buildContent = "buildContent";
    public static final String stageProgress = "stageProgress";
    public static final String reportNum = "reportNum";

    public static final String inspectorName = "inspectorName";
    public static final String inspector = "inspector";
    public static final String purchaseType = "purchaseType";
    public static final String reportRemark = "reportRemark";
    public static final String secondBillId = "secondBillId";
    public static final String firstBillId = "firstBillId";
    public static final String safetyProductId = "safetyProductId";
    public static final String writeAttachment = "writeAttachment";
    public static final String leaveType = "leaveType";

    public static final String peers = "peers";
    public static final String deliveryPic = "deliveryPic";
    public static final String writeData = "writeData";
    public static final String signData = "signData";
    public static final String fileData = "fileData";

    public static final String summary = "summary";
    public static final String regularDate = "regularDate";
    public static final String signReport = "signReport";
    public static final String writeReport = "writeReport";
    public static final String lastWorkDate = "lastWorkDate";
    public static final String auditDept = "auditDept";
    public static final String deliveryDate = "deliveryDate";
    public static final String materialId = "materialId";
    public static final String useNum = "useNum";
    public static final String employmentDate = "employmentDate";
    public static final String applyAmount = "applyAmount";
    public static final String auditNum = "auditNum";
    public static final String useRemark = "useRemark";
    public static final String message = "message";
    public static final String auditRemark = "auditRemark";
    public static final String deliverer = "deliverer";
    public static final String receiver = "receiver";
    public static final String bulidLocation = "bulidLocation";


    public static final String incomeTax = "incomeTax";
    public static final String probationPeriod = "probationPeriod";
    public static final String pname = "pname";
    public static final String numberPlate = "numberPlate";
    public static final String wagesDate = "wagesDate";
    public static final String personNum = "personNum";
    public static final String price = "price";
    public static final String groupId = "groupId";
    public static final String phone = "phone";
    public static final String sex = "sex";
    public static final String deliveryContent = "deliveryContent";
    public static final String workDate = "workDate";
    public static final String LIST_OBJECT = "LIST_OBJECT";
    public static final String pieceWageId = "pieceWageId";
    public static final String GROUP_LIST = "GROUP_LIST";
    public static final String SP_PROJECT_ID = "SP_PROJECT_ID";
    public static final String signValue = "signValue";
    public static final String content = "content";
    public static final String deduction = "deduction";
    public static final String hourNum = "hourNum";
    public static final String pieceNum = "pieceNum";

    public static final String confirmor = "confirmor";
    public static final String trainer = "trainer";
    public static final String time = "time";
    public static final String location = "location";
    public static final String target = "target";
    public static final String planPeoples = "planPeoples";
    public static final String realPeoples = "realPeoples";
    public static final String passed = "passed";
    public static final String Accept = "Accept";

    public static final String accidentOwner = "accidentOwner";
    public static final String securityOwner = "securityOwner";
    public static final String reason = "reason";
    public static final String lossLevel = "lossLevel";
    public static final String directMoneyLoss = "directMoneyLoss";
    public static final String indirectMoneyLoss = "indirectMoneyLoss";
    public static final String emergency = "emergency";
    public static final String handleTime = "handleTime";

    public static final String DICT_ARRAY = "DICT_ARRAY";
    public static final String checker = "checker";
    public static final String checkTime = "checkTime";
    public static final String result = "result";
    public static final String auditorName = "auditorName";
    public static final String standard = "standard";

    public static final String employeeIdList = "employeeIdList";
    public static final String tempEmployeeIdList = "tempEmployeeIdList";
    public static final String attachList = "attachList";
    public static final String LIST_STR = "LIST_STR";
    public static final String projectId = "projectId";
    public static final String reformDesc = "reformDesc";
    public static final String reformTime = "reformTime";
    public static final String qualifyConfigId = "qualifyConfigId";
    public static final String reportResult = "reportResult";
    public static final String processorConfigId = "processorConfigId";
    public static final String confirmResult = "confirmResult";
    public static final String comfirmRemark = "comfirmRemark";
    public static final String mobile = "mobile";
    public static final String fileType = "fileType";
    public static final String reimburseNum = "reimburseNum";
    public static final String returnDate = "returnDate";
    public static final String useDate = "useDate";
    public static final String applyWorkDate = "applyWorkDate";
    public static final String isDevice = "isDevice";
    public static final String isEmployee = "isEmployee";
    public static final String category = "category";
    public static final String isPlan = "isPlan";
    public static final String totalWage = "totalWage";
    public static final String remark = "remark";
    public static final String workerIdList = "workerIdList";
    public static final String planDate = "planDate";
    public static final String amount = "amount";
    public static final String auditResult = "auditResult";
    public static final String planNum = "planNum";
    public static final String designNum = "designNum";
    public static final String workerId = "workerId";
    public static final String payType = "payType";
    public static final String usePosition = "usePosition";
    public static final String receiveNum = "receiveNum";
    public static final String archDrawAuditCertNo = "archDrawAuditCertNo";
    public static final String detectCertNo = "detectCertNo";
    public static final String prospectUnit = "prospectUnit";
    public static final String bankName = "bankName";
    public static final String informNameList = "informNameList";
    public static final String changePlace = "changePlace";
    public static final String bankAccount = "bankAccount";
    public static final String designDraw = "designDraw";
    public static final String designDrawNo = "designDrawNo";
    public static final String auditor = "auditor";
    public static final String wage = "wage";
    public static final String recruitPost = "recruitPost";
    public static final String IS_FIRST_LUNCHER_SP = "IS_FIRST_LUNCHER_SP";
    public static final String recruitNum = "recruitNum";
    public static final String deviceId = "deviceId";
    public static final String SP_PROJECT_IMG_URL = "SP_PROJECT_IMG_URL";
    public static final String IS_FIRST_SHOW_GUILD = "IS_FIRST_SHOW_GUILD";
    public static final String workerName = "workerName";
    public static final String Material_Category = "Material_Category";
    public static final String Device_Category = "Material_Category";
}
